steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/arunmulka-papajohns/gcp-cd-codelab-spinnaker"]
    env: ["PROJECT_ROOT=github.com/arunmulka-papajohns/gcp-cd-codelab-spinnaker"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/cicd-infrastructure-196017/gcp-cd-codelab-spinnaker:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/cicd-infrastructure-196017/gcp-cd-codelab-spinnaker:$REVISION_ID"
